### ISSUE TITLE
Groovy scripts port problem

### ISSUE THREAD

**Issue by pwalczysko** [ome/omero-guide-fiji#15]
The script mentioned in https://omero-guides.readthedocs.io/en/latest/fiji/docs/threshold_scripting.html, namely

1. https://omero-guides.readthedocs.io/en/latest/_downloads/696c96fdd4194bf64b2366851acdcb55/analyse_dataset_save_rois_and_summary_table.groovy
2. https://omero-guides.readthedocs.io/en/latest/_downloads/83bc85e9be03eb62854d6e7a8be0f354/idr0021.groovy

crash on the connection of the port when not using websockets. The swap of ``443`` port for ``4064`` fixes the problem. 

@jburel

**Comment by jburel** [comment]
https://github.com/ome/omero-guide-fiji/pull/16
